enabled: true
default:
  image:
    repository: ghcr.io/elastic/opentelemetry-demo
    tag: 2.2.1
  envOverrides:
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['app.kubernetes.io/component']
    - name: OTEL_K8S_NAMESPACE
      valueFrom:
        fieldRef:
         apiVersion: v1
         fieldPath: metadata.namespace
    - name: OTEL_K8S_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: OTEL_K8S_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: OTEL_K8S_POD_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: 'service.name=$(OTEL_SERVICE_NAME),service.instance.id=$(OTEL_K8S_POD_UID),service.namespace=opentelemetry-demo,k8s.namespace.name=$(OTEL_K8S_NAMESPACE),k8s.node.name=$(OTEL_K8S_NODE_NAME),k8s.pod.name=$(OTEL_K8S_POD_NAME),k8s.pod.uid=$(OTEL_K8S_POD_UID)'
    - name: OTEL_COLLECTOR_NAME
      value: "opentelemetry-kube-stack-daemon-collector.opentelemetry-operator-system.svc.cluster.local"

components:
  fraud-detection:
    resources:
      limits:
        memory: 512Mi
  kafka:
    resources:
      limits:
        memory: 800Mi

  load-generator:
    envOverrides:
      - name: LOCUST_BROWSER_TRAFFIC_ENABLED
        value: "false"

  frontend-proxy:
    envOverrides:
      # This is set in .env file for Docker deployments, but it is not included upstream in the Helm chart, so we set it here.
      - name: ENVOY_ADDR
        value: "0.0.0.0"
      - name: TELEMETRY_DOCS_HOST
        value: "telemetry-docs"
      - name: TELEMETRY_DOCS_PORT
        value: "8000"
  flagd:
    sidecarContainers:
      - name: flagd-ui
        useDefault:
          env: true
        service:
          port: 4000
        env:
          - name: FLAGD_METRICS_EXPORTER
            value: otel
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://$(OTEL_COLLECTOR_NAME):4318
          - name: FLAGD_UI_PORT
            value: "4000"
          - name: SECRET_KEY_BASE
            value: yYrECL4qbNwleYInGJYvVnSkwJuSQJ4ijPTx5tirGUXrbznFIBFVJdPl5t6O9ASw
          - name: PHX_HOST
            value: localhost

        volumeMounts:
          - name: config-rw
            mountPath: /app/data
  product-catalog:
    initContainers:
      - name: wait-for-postgresql
        image: busybox:latest
        command: ["sh", "-c", "until nc -z -v -w30 postgresql 5432; do echo waiting for postgresql; sleep 2; done;"]
    envOverrides:
      - name: OTEL_CONFIG_FILE
        value: /otel-config.yml
    mountedConfigMaps:
      - name: product-catalog-otel-config
        mountPath: /otel-config.yml
        subPath: otel-config.yml
        data:
          otel-config.yml: |
            file_format: "1.0"
            disabled: false
            logger_provider:
              processors:
                - batch:
                    exporter:
                      otlp_grpc:
                        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
            meter_provider:
              readers:
                - periodic:
                    exporter:
                      otlp_grpc:
                        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
                        temporality_preference: ${OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE:-cumulative}
            tracer_provider:
              processors:
                - batch:
                    exporter:
                      otlp_grpc:
                        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
            propagator:
              composite:
                - tracecontext:
                - baggage:
            resource:
              attributes_list: ${OTEL_RESOURCE_ATTRIBUTES}

  llm:
    enabled: false
  product-reviews:
    enabled: false

opentelemetry-collector:
  enabled: false

opensearch:
  enabled: false

grafana:
  enabled: false

jaeger:
  enabled: false

prometheus:
  enabled: false
